### ISSUE TITLE
Relative URLs don't work

### ISSUE THREAD

**Issue by pmorch** [FF-Remote-Control/FF-Remote-Control#1]
Posted on http://groups.google.com/group/mozilla.dev.extensions/browse_frm/thread/6cacc96b42a04e73 :

I expect that on e.g. http://www.mozilla.org a command of
window.location='foo.html' should open http://www.mozilla.org/foo.html
. That is what would happen if it were called on the page. But instead
it redirects to jar:file:///usr/lib/firefox-3.6.17/chrome/browser.jar!/
content/browser/foo.html . I've seen this asked other places too [2]
[3], but I didn't find any good answers. In [3], Boris Zbarsky says
> When we change the base URI behavior to match the W3C proposal and take the base
> URI from the window the XMLHttpRequest object was created on, this might get better.
But as my window.location example illustrates, this seems broader than
XMLHttpRequest.

2: http://forums.mozillazine.org/viewtopic.php?f=19&t=1517525
3: http://groups.google.com/group/mozilla.dev.tech.xpcom/browse_frm/thread/1883519f1b24f91d/23fd1e82e31f84ff?lnk=gst&q=help+with+evalInSandbox#23fd1e82e31f84ff

**Comment by nneonneo** [comment]
This seems to no longer be the case; closing.
