### ISSUE TITLE
automatic start won't work under linux

### ISSUE THREAD

**Issue by jollyzsher** [FF-Remote-Control/FF-Remote-Control#10]
Hi. 

The feature "start automatically" doesn't seem to work under linux.
I used 
FIREFOX_START_REMOTE_CONTROL=1 firefox 
or 
export FIREFOX_START_REMOTE_CONTROL=1
firefox
to start the firefox, but won't start automatically. Yes the button is visible.

I even edited the usual wrapper script in /usr/bin/firefox and exported the variable there. Doesn't work either.

command-line -remote-control doesn't work either.

BTW: there is a typo in the README, one "\" too much in the name of the variable...

Any chance that I make a mistake or is there a bug?

Thanks,
Tobias

**Comment by funivan** [comment]
Close due to non activity
