### ISSUE TITLE
Installed, but doesn't respond

### ISSUE THREAD

**Issue by retorquere** [FF-Remote-Control/FF-Remote-Control#13]
When I have RC disabled, netcat (as expected) does nothing; when I enable RC and type:

C:\>echo "window.location='http:/www.google.com/'" | nc localhost 32000   

I get

{"result":"window.location='http:/www.google.com/'"}

but I see nothing happening in firefox, and netcat doesn't return to the prompt.

**Comment by nneonneo** [comment]
Your problem is that the Windows command-prompt `echo` is sending the `"` characters literally, so the following is sent to Remote Control:

    "window.location='http:/www.google.com/'"

and so the result is simply a string.

Instead, do

    echo window.location='http://www.google.com/' | nc localhost 32000 

and it should work.

**Comment by retorquere** [comment]
That did it (although I had to do window.location.assign("http://www.google.com/") rather than http://www.google.com/)
