### ISSUE TITLE
Feature request: Dynamic port assignment

### ISSUE THREAD

**Issue by emccrory** [FF-Remote-Control/FF-Remote-Control#18]
In my application, I have two large HDTVs running FireFox in Kiosk mode, each displaying its own web site.  Right now, this requires two computers, one for each HDTV.  

One computer with two HDMI output ports can drive two HDTVs.  But since only one port is assigned (statically) for the plugin, it is not clear to me how to make this work.  The obvious option (to me) is to allow two instances of FF to be started, each listening on a different port.  I think this would imply that the port is assigned at startup, as opposed to during the setup of the plugin.

Is this possible?  As an new feature?

**Comment by nneonneo** [comment]
@emccrory The way I've been doing this is to run two Firefox instances with different *profiles*, with a different port number in each profile. You can use the `-P` command-line option to specify a profile at startup. Using this approach, you'd use the Profile Manager:

    firefox -profileManager

to make two profiles called `Profile1` and `Profile2`, then start each of them:

    firefox -P "Profile1" &
    firefox -P "Profile2" &

and then give each one a different port number.
