### ISSUE TITLE
Custom commands

### ISSUE THREAD

**Issue by funivan** [FF-Remote-Control/FF-Remote-Control#24]
Hi to all. 
We have one pull request #21  witch ads tab selector with JSON command
It is very good idea but not the best realization.
This feature is also missed for me.

I thinks we can create some tiny api for custom functions, thet are build inside plugi.
Lets see some examples:
We send `reload`  and our tab gets reloaded. This command is simple alias
We handle command `newtab` with custom callback.

Also we can add `usetab` command with custom regex.
`echo "use_tab /Google/" | nc -q 1 localhost 32000` this command can find tab by name and use it in future.
We can add commands: `use_active_tab` and `use_initial_tab`

One of the cons of this solution is flow of all process. We need to programmatically remember current tab. 
Form the other side we can add specific command for tab switch and other manipulation in to our string;

`echo ":use_tab /Google/; :reload; console.log(1)"` This can be interpreted like following:
1. Use tab in our flow
2. Reload tab
3. Run javascript

**Comment by nneonneo** [comment]
Hmm, this will require some actual API hooks, which will make the remote control architecture more complex (since now we have to pass the commands through to the parent and ask it to perform certain actions).

**Comment by funivan** [comment]
How do you think: what is the best solution to execute command in other tab?

**Comment by nneonneo** [comment]
Hmm, perhaps piggybacking on the current support for "active tab" is the
way to go. Instead of only the active tab, we can do some parsing to figure
out which tab to route the command to. The annoying thing is that the tab
selection command should not be valid JS, so as to avoid interfering with
normal use. I like the idea of starting the line with a colon to signify
that a special tab selection command will be used.

**Comment by funivan** [comment]
OK. I will prototype some features next week.

**Comment by nneonneo** [comment]
Great, thank you!

**Comment by funivan** [comment]
Hello @nneonneo 
There are 2 version.
Test code for fist version. (with option activeTab=true)
```sh
#!/usr/bin/env bash
echo "window.location='http://google.ua'" | nc -q 1 localhost 32000      
echo newtab | nc -q 1 localhost 32000      
echo "window.location='https://github.com/'" | nc -q 1 localhost 32000      
echo "newtab" | nc -q 1 localhost 32000      
echo "/*:use_tab /google/i*/ window.location='http://gist.github.com'" | nc -q 1 localhost 32000      
    
```
Special syntax is /*:(custom command name) (custom argument)*/

In some cases it is cool but there is no way to add more flexible commands for example retrieve tabs list.

I implemented other version:
https://github.com/funivan/FF-Remote-Control/commit/8c0b123164e95f14957b0c8382996adaf6164ee9

```sh
#!/usr/bin/env bash

echo newtab | nc -q 1 localhost 32000      
echo "//:use_active_tab" | nc -q 1 localhost 32000
echo "window.location='http://google.ua'" | nc -q 1 localhost 32000      

echo newtab | nc -q 1 localhost 32000
echo "//:use_active_tab" | nc -q 1 localhost 32000
echo "window.location='http://github.com'" | nc -q 1 localhost 32000


echo "//:get_tab_list" | nc -q 1 localhost 32000      
      
echo "//:use_tab /google/i" | nc -q 1 localhost 32000
echo " window.location='http://gist.github.com'" | nc -q 1 localhost 32000
```

I prefer version 2. We can add more custom commands and they will have one single state (they return some result to us).

**Comment by funivan** [comment]
ping @nneonneo

**Comment by nneonneo** [comment]
I think either version is fine. The code seems reasonable - could you
squash the commits into a single patch and submit a pull request?


ivan <notifications@github.com>于2016年1月13日 周三上午9:47写道：

**Comment by funivan** [comment]
I will merge commits at 2016-01-14 and create new PR

**Comment by funivan** [comment]
@nneonneo done. New PR #27
