### ISSUE TITLE
Update addon

### ISSUE THREAD

**Issue by funivan** [FF-Remote-Control/FF-Remote-Control#30]
Hello. latest version of remote control is `2.0.0.1-signed` When it will be updated to the latest? Thanks )

**Comment by nneonneo** [comment]
I'll get on this this weekend. However right now I'm worried that the add on will be rejected as it isn't compatible with the Electrolysis browser re-architect, and I'm not yet sure how to handle that best.

**Comment by funivan** [comment]
ping

**Comment by nneonneo** [comment]
So the patches we've been applying are for the 1.x branch, so I'm not sure if we should submit it.

The bigger issue is that Electrolysis has now hit beta, so it won't be long before this addon just stops working entirely. Still not sure how to handle this in a nice way - I think content scripts are the only option, and in theory the 2.x version should have made it easier to go to content scripts. Still not sure though.

**Comment by funivan** [comment]
Can you post some links to Electrolysis

**Comment by nneonneo** [comment]
https://wiki.mozilla.org/Electrolysis (overview of the project and goals)

https://developer.mozilla.org/en-US/Firefox/Multiprocess_Firefox (technical
dive including an add-on migration guide and API details)

The gist is that Firefox is going multi-process in a future build, in which
web content runs in processes separate from the main browser UI (chrome
process). Content processes will be sandboxed for security and efficiency
concerns. Communication across the content-chrome boundary is done via IPC,
and we get higher-level chrome JavaScript APIs to simplify this.

Currently Remote Control requires the main browser hold a server socket,
and which gives commands to the individual browser tabs. In e10s
(electrolysis) Firefox, the individual browser tabs will have to run
content scripts (like grease monkey scripts but with hooks to communicate
with addons living in the chrome process).

**Comment by klausenbusk** [comment]
I get `{"error":"request aborted: tab control shutdown"}`, sometimes* when I try to change the url with:
```
echo "window.location=\"http://foo.bar\"" | nc -w 1 localhost 32000
```
with Firefox 50.0b11 from 28. Oct.
I'm not sure if it is caused by the e10s or something else? Any idea?
I just switched to Firefox 50.0 release, let see if that change anything.

*It looks like it works the first time/a few time, and then I just get that error forever.

**Comment by klausenbusk** [comment]
Disabling e10s with:
```
user_pref("browser.tabs.remote.autostart", false);
```
doesn't seems to help. Weird.
Firefox gives errors like:
```
console.error: remote-control: 
  input no longer available: [Exception... "Component returned failure code: 0x80470002 (NS_BASE_STREAM_CLOSED) [nsIInputStream.available]"  nsresult: "0x80470002 (NS_BASE_STREAM_CLOSED)"  location: "JS frame :: resource://gre/modules/commonjs/toolkit/loader.js -> resource://remote-control-at-morch-dot-com/clienthandler.js :: RemoteControlClientHandler.prototype.onInputStreamReady :: line 56"  data: no]
```

**Comment by pmorch** [comment]
See #37.
