### ISSUE TITLE
Replacement directly from Firefox (for many use cases of FF)

### ISSUE THREAD

**Issue by emccrory** [FF-Remote-Control/FF-Remote-Control#40]
Note that Firefox 57 will have a new Selineum-like control feature set:

https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette

This will likely be the way I go, once our (lovely!) FF_Remote-Control plugin stops working.

I hope this helps someone.

**Comment by pmorch** [comment]
Thanks for the great info, @emccrory.

As mentioned in #37, this project is likely dead now that FF57 has been released. Marionette is one more nail in the coffin! ;-)

That along with the fact that here isn't anything for us to do on this item, causes me to close this issue right away.
