### ISSUE TITLE
Problems with Preferences Window on Mac OS X 10.8.2

### ISSUE THREAD

**Issue by nonzer0value** [FF-Remote-Control/FF-Remote-Control#8]
I haven't had a chance to use this extension yet, but I like the idea (a lot!) and I'm excited to use it as part of my development workflow.

When I click Preferences for this extension, I get exactly this window:

![2013-03-08_10-27-55_remote_control_ff_prefs](https://f.cloud.github.com/assets/508140/237210/65980a10-880d-11e2-9bd6-1b84300cf36d.jpg)

* I cannot resize the window.
* The window provides no capability to scroll to the bottom.

I'm using Firefox 19.0.2 (release channel), on a MBPr (late 2012) running OS X 10.8.2.

Please let me know if there is any more information I can provide.

Thanks!

~nzv

**Comment by funivan** [comment]
@nonzer0value is this issue still unresolved?
