### ISSUE TITLE
Getting "error":"missing } in compound statement" since last update.

### ISSUE THREAD

**Issue by bionpohl** [FF-Remote-Control/FF-Remote-Control#9]
FF-Remote-Control started failing after the update on 3/28.  It doesn't seem to be parsing the JavaScript the way it use to.  This Perl script use to work:

$ remote_firefox.pl -v http://www.google.com
Sent: { var myWindow=window.open('http://www.google.com','www.google.com');
                                                               myWindow.focus();                    }
Responded: {"error":"missing } in compound statement"}
missing } in compound statement
         at /home/f6xzq1q/prgm/remote_firefox.pl line 190, <GEN0> line 1.

This still works:

$ remote_firefox.pl -rv
Sent: reload
Responded: {}

**Comment by nneonneo** [comment]
Drop the `{}` around your input:

    var myWindow=window.open('http://www.google.com','www.google.com'); myWindow.focus();

Then it works fine.
